// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gozbudanjktbfbrejird.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvemJ1ZGFuamt0YmZicmVqaXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NjczMTYsImV4cCI6MjA4NjA0MzMxNn0.WWF7SNVNj51dC4QmN6RKY04CNA3nwVIf9pq2DC7547A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});